// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SAPS.Web.Data;

#nullable disable

namespace SAPS.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20261009032146_EstadoContrasena")]
    partial class EstadoContrasena
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SAPS.Web.Models.Catalogo.Bebida", b =>
                {
                    b.Property<int>("IdBebida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idBebida");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdBebida"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("EstaActivo");

                    b.Property<int?>("IdTamano")
                        .HasColumnType("int")
                        .HasColumnName("idTamano");

                    b.Property<string>("NombreBebida")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Nombre");

                    b.Property<int>("Precio")
                        .HasColumnType("int")
                        .HasColumnName("Precio");

                    b.Property<string>("TipoBebida")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Tipo");

                    b.HasKey("IdBebida")
                        .HasName("PK_Bebida");

                    b.HasIndex("IdTamano")
                        .HasDatabaseName("IX_Bebida_idTamano");

                    b.ToTable("tb_Bebida", "soda", t =>
                        {
                            t.HasCheckConstraint("CK_Bebida_Precio", "[Precio] > 0");

                            t.HasCheckConstraint("CK_Bebida_Tipo", "[Tipo] IN ('Gaseosa','Embotellada','Energizante','Jugo')");
                        });
                });

            modelBuilder.Entity("SAPS.Web.Models.Catalogo.Categoria", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idCategoria");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCategoria"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("EstaActivo");

                    b.Property<string>("NombreCategoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Nombre");

                    b.HasKey("IdCategoria")
                        .HasName("PK_Categoria");

                    b.HasIndex("NombreCategoria")
                        .IsUnique()
                        .HasDatabaseName("UQ_Categoria_Nombre");

                    b.ToTable("tb_Categoria", "soda");
                });

            modelBuilder.Entity("SAPS.Web.Models.Catalogo.Precio", b =>
                {
                    b.Property<int>("IdPrecio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idPrecio");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPrecio"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("EstaActivo");

                    b.Property<DateOnly>("FechaVigenciaDesde")
                        .HasColumnType("date")
                        .HasColumnName("FechaVigenciaDesde");

                    b.Property<DateOnly?>("FechaVigenciaHasta")
                        .HasColumnType("date")
                        .HasColumnName("FechaVigenciaHasta");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int")
                        .HasColumnName("idProducto");

                    b.Property<int?>("IdTamano")
                        .HasColumnType("int")
                        .HasColumnName("idTamano");

                    b.Property<int>("MontoPrecio")
                        .HasColumnType("int")
                        .HasColumnName("Monto");

                    b.HasKey("IdPrecio")
                        .HasName("PK_Precio");

                    b.HasIndex("IdTamano")
                        .HasDatabaseName("IX_Precio_idTamano");

                    b.HasIndex("IdProducto", "IdTamano")
                        .IsUnique()
                        .HasDatabaseName("IX_Precio_idProducto_idTamano")
                        .HasFilter("[EstaActivo] = 1");

                    b.ToTable("tb_Precio", "soda", t =>
                        {
                            t.HasCheckConstraint("CK_Precio_Monto", "[Monto] > 0");

                            t.HasCheckConstraint("CK_Precio_Vigencia", "[FechaVigenciaHasta] IS NULL OR [FechaVigenciaHasta] >= [FechaVigenciaDesde]");
                        });
                });

            modelBuilder.Entity("SAPS.Web.Models.Catalogo.Producto", b =>
                {
                    b.Property<int>("IdProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idProducto");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProducto"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("EstaActivo");

                    b.Property<bool>("EsEspecial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("EsEspecial");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("int")
                        .HasColumnName("idCategoria");

                    b.Property<string>("NombreProducto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Nombre");

                    b.Property<bool>("RequiereTamano")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("TieneTamano");

                    b.HasKey("IdProducto")
                        .HasName("PK_Producto");

                    b.HasIndex("IdCategoria")
                        .HasDatabaseName("IX_Producto_idCategoria");

                    b.ToTable("tb_Producto", "soda");
                });

            modelBuilder.Entity("SAPS.Web.Models.Catalogo.Tamano", b =>
                {
                    b.Property<int>("IdTamano")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idTamano");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTamano"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("EstaActivo");

                    b.Property<string>("NombreTamano")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("Nombre");

                    b.HasKey("IdTamano")
                        .HasName("PK_Tamano");

                    b.HasIndex("NombreTamano")
                        .IsUnique()
                        .HasDatabaseName("UQ_Tamano_Nombre");

                    b.ToTable("tb_Tamano", "soda");
                });

            modelBuilder.Entity("SAPS.Web.Models.Identity.EstadoContrasenaUsuario", b =>
                {
                    b.Property<string>("IdUsuario")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("idUsuario");

                    b.Property<DateTime>("FechaUltimoCambio")
                        .HasColumnType("datetime2");

                    b.HasKey("IdUsuario")
                        .HasName("PK_EstadoContrasena");

                    b.ToTable("tb_EstadoContrasena", (string)null);
                });

            modelBuilder.Entity("SAPS.Web.Models.Pedidos.DetallePedido", b =>
                {
                    b.Property<int>("IdDetallePedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idDetallePedido");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDetallePedido"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int?>("IdBebida")
                        .HasColumnType("int")
                        .HasColumnName("idBebida");

                    b.Property<int>("IdPedido")
                        .HasColumnType("int")
                        .HasColumnName("idPedido");

                    b.Property<int?>("IdPrecio")
                        .HasColumnType("int")
                        .HasColumnName("idPrecio");

                    b.Property<string>("NombreArticulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NombreTamano")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<int>("PrecioUnitario")
                        .HasColumnType("int");

                    b.Property<long>("Subtotal")
                        .HasColumnType("bigint");

                    b.HasKey("IdDetallePedido")
                        .HasName("PK_DetallePedido");

                    b.HasIndex("IdBebida")
                        .HasDatabaseName("IX_DetallePedido_idBebida");

                    b.HasIndex("IdPedido")
                        .HasDatabaseName("IX_DetallePedido_idPedido");

                    b.HasIndex("IdPrecio")
                        .HasDatabaseName("IX_DetallePedido_idPrecio");

                    b.ToTable("tb_DetallePedido", "soda", t =>
                        {
                            t.HasCheckConstraint("CK_DetallePedido_Articulo", "([idPrecio] IS NOT NULL AND [idBebida] IS NULL) OR ([idPrecio] IS NULL AND [idBebida] IS NOT NULL)");

                            t.HasCheckConstraint("CK_DetallePedido_Cantidad", "[Cantidad] > 0");

                            t.HasCheckConstraint("CK_DetallePedido_PrecioUnitario", "[PrecioUnitario] > 0");

                            t.HasCheckConstraint("CK_DetallePedido_Subtotal", "[Subtotal] = CAST([Cantidad] AS bigint) * [PrecioUnitario]");
                        });
                });

            modelBuilder.Entity("SAPS.Web.Models.Pedidos.Pedido", b =>
                {
                    b.Property<int>("IdPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idPedido");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPedido"));

                    b.Property<string>("CodigoColaborador")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("EsPrueba")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaRegistroUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdUsuarioRegistro")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("idUsuario");

                    b.Property<string>("NombreColaborador")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("TipoComida")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<Guid>("TokenRegistro")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Total")
                        .HasColumnType("bigint");

                    b.HasKey("IdPedido")
                        .HasName("PK_Pedido");

                    b.HasIndex("IdUsuarioRegistro")
                        .HasDatabaseName("IX_Pedido_idUsuario");

                    b.HasIndex("TokenRegistro")
                        .IsUnique()
                        .HasDatabaseName("UQ_Pedido_TokenRegistro");

                    b.HasIndex("CodigoColaborador", "FechaRegistroUtc")
                        .HasDatabaseName("IX_Pedido_CodigoColaborador_FechaRegistroUtc");

                    b.ToTable("tb_Pedido", "soda", t =>
                        {
                            t.HasCheckConstraint("CK_Pedido_TipoComida", "[TipoComida] IN ('Desayuno','Almuerzo','Merienda')");

                            t.HasCheckConstraint("CK_Pedido_Total", "[Total] > 0");
                        });
                });

            modelBuilder.Entity("SAPS.Web.Models.Rrhh.ColaboradorRrhh", b =>
                {
                    b.Property<int>("IdColaborador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idColaborador");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdColaborador"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<bool>("EstaActivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("RutaFoto")
                        .HasMaxLength(260)
                        .IsUnicode(false)
                        .HasColumnType("varchar(260)");

                    b.HasKey("IdColaborador")
                        .HasName("PK_Colaborador");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("UQ_Colaborador_Codigo");

                    b.ToTable("tb_Colaborador", "rrhh");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SAPS.Web.Models.Catalogo.Bebida", b =>
                {
                    b.HasOne("SAPS.Web.Models.Catalogo.Tamano", "Tamano")
                        .WithMany("Bebidas")
                        .HasForeignKey("IdTamano")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Bebida_Tamano");

                    b.Navigation("Tamano");
                });

            modelBuilder.Entity("SAPS.Web.Models.Catalogo.Precio", b =>
                {
                    b.HasOne("SAPS.Web.Models.Catalogo.Producto", "Producto")
                        .WithMany("Precios")
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Precio_Producto");

                    b.HasOne("SAPS.Web.Models.Catalogo.Tamano", "Tamano")
                        .WithMany("Precios")
                        .HasForeignKey("IdTamano")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Precio_Tamano");

                    b.Navigation("Producto");

                    b.Navigation("Tamano");
                });

            modelBuilder.Entity("SAPS.Web.Models.Catalogo.Producto", b =>
                {
                    b.HasOne("SAPS.Web.Models.Catalogo.Categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Producto_Categoria");

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("SAPS.Web.Models.Identity.EstadoContrasenaUsuario", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithOne()
                        .HasForeignKey("SAPS.Web.Models.Identity.EstadoContrasenaUsuario", "IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_EstadoContrasena_Usuario");
                });

            modelBuilder.Entity("SAPS.Web.Models.Pedidos.DetallePedido", b =>
                {
                    b.HasOne("SAPS.Web.Models.Catalogo.Bebida", null)
                        .WithMany()
                        .HasForeignKey("IdBebida")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_DetallePedido_Bebida");

                    b.HasOne("SAPS.Web.Models.Pedidos.Pedido", "Pedido")
                        .WithMany("Detalles")
                        .HasForeignKey("IdPedido")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_DetallePedido_Pedido");

                    b.HasOne("SAPS.Web.Models.Catalogo.Precio", null)
                        .WithMany()
                        .HasForeignKey("IdPrecio")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_DetallePedido_Precio");

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("SAPS.Web.Models.Pedidos.Pedido", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("IdUsuarioRegistro")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Pedido_Usuario");
                });

            modelBuilder.Entity("SAPS.Web.Models.Catalogo.Categoria", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("SAPS.Web.Models.Catalogo.Producto", b =>
                {
                    b.Navigation("Precios");
                });

            modelBuilder.Entity("SAPS.Web.Models.Catalogo.Tamano", b =>
                {
                    b.Navigation("Bebidas");

                    b.Navigation("Precios");
                });

            modelBuilder.Entity("SAPS.Web.Models.Pedidos.Pedido", b =>
                {
                    b.Navigation("Detalles");
                });
#pragma warning restore 612, 618
        }
    }
}
